services:
  weather_agent:
    build: .
    container_name: weather_pipeline_p9
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
    networks:
      - weather_net
    environment:
      - PYTHONUNBUFFERED=1 #tylko do logów

networks:
  weather_net:
    driver: bridge # na wszelki żeby na pewno był online